import requests
import json
import logging
from typing import AsyncGenerator

logger = logging.getLogger(__name__)

# USE ONLY llama3.1:8b
OLLAMA_URL = "http://localhost:11434/api/chat"
MODEL_NAME = "llama3.1:8b"


def call_llm(messages, max_tokens=256, temperature=0.2):
    """
    Call Ollama LLM using /api/chat endpoint with llama3.1:8b (Non-streaming)
    
    Args:
        messages: List of message dicts with 'role' and 'content'
        max_tokens: Maximum tokens to generate
        temperature: Sampling temperature (0.0 - 1.0)
    
    Returns:
        Dict with 'message' containing 'content' key
    """
    try:
        payload = {
            "model": MODEL_NAME,
            "messages": messages,
            "stream": False,
            "options": {
                "temperature": temperature,
                "num_predict": max_tokens
            }
        }
        
        logger.info(f"Calling Ollama with model: {MODEL_NAME}, messages: {len(messages)}")
        
        resp = requests.post(OLLAMA_URL, json=payload, timeout=300)
        resp.raise_for_status()
        
        result = resp.json()
        
        if "message" in result:
            response_text = result["message"].get("content", "")
        else:
            logger.warning(f"Unexpected Ollama response format: {result}")
            response_text = str(result)
        
        logger.info(f"LLM response received: {len(response_text)} chars")
        
        return {
            "message": {
                "content": response_text.strip()
            }
        }
        
    except requests.exceptions.Timeout:
        logger.error(f"LLM request timed out after 300s with model {MODEL_NAME}")
        raise Exception("LLM request timed out - model may be too slow")
    
    except requests.exceptions.HTTPError as e:
        logger.error(f"HTTP error from Ollama: {e.response.status_code} - {e.response.text}")
        raise Exception(f"Ollama HTTP error: {e.response.status_code}")
    
    except requests.exceptions.RequestException as e:
        logger.error(f"LLM request failed: {e}")
        raise Exception(f"Failed to connect to Ollama: {e}")
    
    except Exception as e:
        logger.error(f"Unexpected error calling LLM: {e}", exc_info=True)
        raise Exception(f"LLM error: {e}")


async def call_llm_streaming(messages, max_tokens=256, temperature=0.2) -> AsyncGenerator[str, None]:
    """
    Call Ollama LLM with streaming support - yields tokens as they arrive
    
    Args:
        messages: List of message dicts with 'role' and 'content'
        max_tokens: Maximum tokens to generate
        temperature: Sampling temperature (0.0 - 1.0)
    
    Yields:
        String tokens as they're generated by the LLM
    """
    try:
        payload = {
            "model": MODEL_NAME,
            "messages": messages,
            "stream": True,
            "options": {
                "temperature": temperature,
                "num_predict": max_tokens
            }
        }
        
        logger.info(f"Starting streaming call to Ollama with model: {MODEL_NAME}")
        
        resp = requests.post(OLLAMA_URL, json=payload, stream=True, timeout=300)
        resp.raise_for_status()
        
        full_response = []
        
        for line in resp.iter_lines():
            if line:
                try:
                    chunk = json.loads(line.decode('utf-8'))
                    
                    if "message" in chunk and "content" in chunk["message"]:
                        content = chunk["message"]["content"]
                        if content:
                            full_response.append(content)
                            yield content
                    
                    # Check if streaming is done
                    if chunk.get("done", False):
                        logger.info(f"Streaming completed. Total tokens: {len(''.join(full_response))}")
                        break
                        
                except json.JSONDecodeError as e:
                    logger.warning(f"Failed to decode JSON chunk: {e}")
                    continue
        
    except requests.exceptions.Timeout:
        logger.error(f"Streaming LLM request timed out with model {MODEL_NAME}")
        raise Exception("Streaming request timed out")
    
    except requests.exceptions.HTTPError as e:
        logger.error(f"HTTP error during streaming: {e.response.status_code}")
        raise Exception(f"Ollama streaming error: {e.response.status_code}")
    
    except Exception as e:
        logger.error(f"Streaming LLM error: {e}", exc_info=True)
        raise Exception(f"Streaming error: {e}")
